/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkersAddRouteImport } from './routes/workers.add'
import { Route as WorkAddRouteImport } from './routes/work.add'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersAddRoute = WorkersAddRouteImport.update({
  id: '/workers/add',
  path: '/workers/add',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkAddRoute = WorkAddRouteImport.update({
  id: '/work/add',
  path: '/work/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work/add': typeof WorkAddRoute
  '/workers/add': typeof WorkersAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work/add': typeof WorkAddRoute
  '/workers/add': typeof WorkersAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work/add': typeof WorkAddRoute
  '/workers/add': typeof WorkersAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/work/add' | '/workers/add'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/work/add' | '/workers/add'
  id: '__root__' | '/' | '/work/add' | '/workers/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkAddRoute: typeof WorkAddRoute
  WorkersAddRoute: typeof WorkersAddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/add': {
      id: '/workers/add'
      path: '/workers/add'
      fullPath: '/workers/add'
      preLoaderRoute: typeof WorkersAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/add': {
      id: '/work/add'
      path: '/work/add'
      fullPath: '/work/add'
      preLoaderRoute: typeof WorkAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkAddRoute: WorkAddRoute,
  WorkersAddRoute: WorkersAddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
