/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalculatorRouteImport } from './routes/_authenticated/calculator'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedWorkersAddRouteImport } from './routes/_authenticated/workers.add'
import { Route as AuthenticatedWorkAddRouteImport } from './routes/_authenticated/work.add'
import { Route as AuthenticatedPaymentsAddRouteImport } from './routes/_authenticated/payments.add'
import { Route as AuthenticatedClientsAddRouteImport } from './routes/_authenticated/clients.add'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalculatorRoute = AuthenticatedCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkersAddRoute = AuthenticatedWorkersAddRouteImport.update({
  id: '/workers/add',
  path: '/workers/add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkAddRoute = AuthenticatedWorkAddRouteImport.update({
  id: '/work/add',
  path: '/work/add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsAddRoute =
  AuthenticatedPaymentsAddRouteImport.update({
    id: '/payments/add',
    path: '/payments/add',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsAddRoute = AuthenticatedClientsAddRouteImport.update({
  id: '/clients/add',
  path: '/clients/add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof AuthenticatedCalculatorRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/add': typeof AuthenticatedClientsAddRoute
  '/payments/add': typeof AuthenticatedPaymentsAddRoute
  '/work/add': typeof AuthenticatedWorkAddRoute
  '/workers/add': typeof AuthenticatedWorkersAddRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/calculator': typeof AuthenticatedCalculatorRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/': typeof AuthenticatedIndexRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/add': typeof AuthenticatedClientsAddRoute
  '/payments/add': typeof AuthenticatedPaymentsAddRoute
  '/work/add': typeof AuthenticatedWorkAddRoute
  '/workers/add': typeof AuthenticatedWorkersAddRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calculator': typeof AuthenticatedCalculatorRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/clients/add': typeof AuthenticatedClientsAddRoute
  '/_authenticated/payments/add': typeof AuthenticatedPaymentsAddRoute
  '/_authenticated/work/add': typeof AuthenticatedWorkAddRoute
  '/_authenticated/workers/add': typeof AuthenticatedWorkersAddRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calculator'
    | '/dashboard'
    | '/reports'
    | '/transactions'
    | '/clients/$id'
    | '/clients/add'
    | '/payments/add'
    | '/work/add'
    | '/workers/add'
    | '/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/calculator'
    | '/dashboard'
    | '/reports'
    | '/transactions'
    | '/'
    | '/clients/$id'
    | '/clients/add'
    | '/payments/add'
    | '/work/add'
    | '/workers/add'
    | '/clients'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calculator'
    | '/_authenticated/dashboard'
    | '/_authenticated/reports'
    | '/_authenticated/transactions'
    | '/_authenticated/'
    | '/_authenticated/clients/$id'
    | '/_authenticated/clients/add'
    | '/_authenticated/payments/add'
    | '/_authenticated/work/add'
    | '/_authenticated/workers/add'
    | '/_authenticated/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculator': {
      id: '/_authenticated/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof AuthenticatedCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workers/add': {
      id: '/_authenticated/workers/add'
      path: '/workers/add'
      fullPath: '/workers/add'
      preLoaderRoute: typeof AuthenticatedWorkersAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work/add': {
      id: '/_authenticated/work/add'
      path: '/work/add'
      fullPath: '/work/add'
      preLoaderRoute: typeof AuthenticatedWorkAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/add': {
      id: '/_authenticated/payments/add'
      path: '/payments/add'
      fullPath: '/payments/add'
      preLoaderRoute: typeof AuthenticatedPaymentsAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/add': {
      id: '/_authenticated/clients/add'
      path: '/clients/add'
      fullPath: '/clients/add'
      preLoaderRoute: typeof AuthenticatedClientsAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalculatorRoute: typeof AuthenticatedCalculatorRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedClientsAddRoute: typeof AuthenticatedClientsAddRoute
  AuthenticatedPaymentsAddRoute: typeof AuthenticatedPaymentsAddRoute
  AuthenticatedWorkAddRoute: typeof AuthenticatedWorkAddRoute
  AuthenticatedWorkersAddRoute: typeof AuthenticatedWorkersAddRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalculatorRoute: AuthenticatedCalculatorRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedClientsAddRoute: AuthenticatedClientsAddRoute,
  AuthenticatedPaymentsAddRoute: AuthenticatedPaymentsAddRoute,
  AuthenticatedWorkAddRoute: AuthenticatedWorkAddRoute,
  AuthenticatedWorkersAddRoute: AuthenticatedWorkersAddRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
